
pfQuest_questcache = {
	["Dragonkin Menace:54:Slay 15 Black Broodlings, 10 Black Dragonspawn, 4 Black Wyrmkin and 1 Black Drake. Return to Helendis Riverhorn when the task is complete.:Life in the Burning Steppes is rife with conflict.\n\nJust look at this place! We know very little of what happened to these buildings, but we do know that at one time, before the great explosion, this was all part of the Redridge mountain range.\n\nEnough lamenting! We have a problem, Fanatique. You may have noticed the dragonkin below this ridge. We need assistance in pushing them back. Kill as many as you can and return to me. Succeed and perhaps we can talk of other things.\n"] = {
		[1] = 4182,
	},
	["Smelting Dreamsteel:60:Gather 15 Bright Dream Shards for Tanthos Everbreeze at Nordanaar in Hyjal.:The ability to smelt Dreamsteel is an art all in itself. Whilst the difficulty to actually create patterns using Dreamsteel Bars is complicated, it does not overshadow the smelting process.\n\nIf you wish to learn how to create your own Dreamsteel Bars and not rely on others, gather for me fifteen Bright Dream Shards as a showing of your loyalty to the World Tree."] = {
		[1] = 40886,
	},
	["Gurubashi, Vilebranch, and Witherbark Coins:60::I seek the Paragons of Power known as the Coins of the Tribes.  They are the currency used by the various denizens of Zul'Gurub, and each is imbued with subtle but powerful mojo.\n\nThere are nine distinct kinds to be found.  Some are sought after by my compatriots for various armors they offer Zandalar heroes.  Should you have any extra, I will trade you one of our Honor Tokens for a set of three.  You may use the Tokens with Rin'wosho the Trader; he offers our heroes special items for them."] = {
		[1] = 8238,
	},
	["Earlwake No More:60:The lead runs dry, Archibald is of no help. But perhaps the description of the orc he provided can aid in the search for Tillia's necklace. :Yer looking for the Earlwake Estate? Don't make me laugh, that wretched place is nothing but a memory, burned to the ground years ago, and all my dreams and hopes with it. What ya see before ya is all that's left of the Earlwake name - this pathetic, worthless pile of failures. \n\n<A guttural burp escapes him and vomit follows suit, dripping unto his already dirty shirt.>\n\nWe lost everything, everything! They looted our treasury and murdered anyone inside the house. Even... even my beloved Georgina... Seeing her lie there, lifeless... the diamond necklace I stole for her, still shining... That beast, that orc ripped it from her - I may be blind but I can still see it... in my head! How he laughed and worshipped his warchief, that Doomhammer! I will never forget that monster, ever! Had it been me, I would've slaughtered them all, not put them into camps!\n\nWhatever ya want from me, I don't have it, stop asking me questions! Piss off and leave me be!"] = {
		[1] = "Earlwake No More",
	},
	["The Human, Ras Frostwhisper:60:Travel to the Arathi Highlands, to the ruins of Stromgarde. Search Stromgarde for a Keepsake of Remembrance. If you find such an item, return with it to Magistrate Marduke.:The undead fear life just as the living fear death. It is not unusual for a sentient undead being to completely destroy all remnants of his or her previous life after having turned.\n\nUnfortunately, in order to create an artifact capable of reverting Ras Frostwhisper to a mortal, we must have a keepsake from his years among the living.\n\nYou must venture to the ruined city of Stromgarde, Frostwhisper's home, and search for such an item. May luck be with you, Fanatique."] = {
		[1] = 5461,
	},
	["Kharan Mighthammer:59:Travel to Blackrock Depths and find Kharan Mighthammer.\n\nThe King mentioned that Kharan was being held prisoner there - perhaps you should try looking for a prison.:You have been to the smoldering ruins of Thaurissan? Did you happen to run into a pitiful lout named Kharan Mighthammer? The dwarf that was supposedly watching over my baby girl!\n\n<The King sobs.>\n\nAnd now she's gone, Unknown!\n\nI have had my men turn the Steppes upside down. The only clue they have as to the whereabouts of my daughter is that she may be inside the Depths. For all I know, she could be dead!\n\nKharan is supposedly being held prisoner there... find him! I want answers!"] = {
		[1] = 4341,
	},
	["Paragons of Power: The Freethinker's Belt:61:Bring Jin'rokh the Breaker a Primal Hakkari Shawl.  You must also have a reputation equal to or greater than Honored with the Zandalar Tribe.\n\nJin'rokh the Breaker is located on Yojamba Isle, Stranglethorn Vale.:Your beliefs are alien to us, heathen.  Ancient Zandalar were once branded as heretics.  This was when the Gurubashi Empire was strong.  Heathens dared to challenge the priest of Hakkar.  Heathens then were hunted and killed as vermin.  Those heathens never wavered in their fight against the Blood God.  We honor the price they paid.  They are the freethinkers.\n\nDestroy the minions of Hakkar in Zul'Gurub.  Bring me the Paragons of Power I seek.  Success will be greatly rewarded.\n\nGo."] = {
		[1] = 8054,
	},
	["Lawbringer's Hands:60:Trade in your current item for the item that best suits your needs.:You wear the guise of the Lawbringer, Paladin. I see it shine under the light of your faith, yet it seems rather dim. Perhaps the one you carry is not suited for the tasks you are willing to perform.\n\n<Geldra hums for a few seconds.>\n\nHand it here and tell me, by which law shall your hand be guided?"] = {
		[1] = "Lawbringer's Hands",
	},
	["Dangerous Love:60:Get a Stormwind Guard's Card and return it to Aristan Mottar in Stormwind.:There's something unnatural about this epidemic of love. It's not proper, it's an eyesore, and at worst, it could be a threat to the the safety of the Alliance itself.\n\nJust think: what if the guards have been taken in by this strange affliction? Something must be done.\n\nGo to one of the guards here in Stormwind and see if they've been caught up in this foolishness."] = {
		[1] = 8903,
	},
	["The Binding of Xanthar:60:Gather the Upper Binding of Xanthar and the Lower Binding of Xanthar for Hanvar the Righteous in the small church outside of Karazhan.:Some years ago, a rare and powerful item was stored inside of this church. I have been cursed to remain ever since its disappearance years ago. If you could recover this item and return it to Karazhan, I would be more than thankful.\n\nThe Binding was torn apart before it was ever stolen, both halves now rest with separate owners. The first was taken by a hermit mage who held no affiliations, his accent certainly sounded like he came from the north.\n\nThe second half of the binding was taken by a man of faith, of vigilance, wearing red cloth and bearing the symbol of the Light itself. His ravings almost sounded mad!\n\nGather me both the upper and lower half of the binding, and I can make it whole."] = {
		[1] = 41015,
	},
	["The Active Agent:60:Travel to Stratholme and search the ziggurats. Find and return new Scourge Data to Betina Bigglezink.\n:You will have to delve deeper into Stratholme, Fanatique.\n\nBeyond the first gates you will find the ziggurats. We know that the Scourge draws great power from these structures. Search the Ziggurats and return with any information that you may discover.\n"] = {
		[1] = 5213,
	},
	["The Mystery of Karazhan I:60:Search for the Pendant of Ardan, rumored to be held by the ogre Var'zhog, collect it, and return to Magus Ariden Dusktower in Deadwind Pass.:I have ventured to this rather decrepid, and lonely place to investigate the mysteries surrounding Karazhan. It has long since loomed over this land with a great power emitting from it. While the tower is impressive, it does not boast the power it once held under the rule of Medivh.\n\nMy analysis of the tower is that the growing power does not come from above, but below. There have always been tales of a crypt that stretched deep beneath Karazhan, perhaps they may be true.\n\nThe first thing I ask of you is to search for a long lost pendant, rumored to have been taken from the ruins of Karazhan some time ago. It will be needed to magically attune the key for our purposes. My suspicion is that the ogre's of the region have taken hold of it. An ogre magi by the name of Var'zhog has grown to some renown as of recently, no doubt he holds the pendant."] = {
		[1] = 40311,
	},
	["Shard Harmonization:60::"] = {
		[1] = 40813,
	},
	["Blackhand's Command:60:That is one stupid orc. It would appear as if you need to find this brand and gain the Mark of Drakkisath in order to access the Orb of Command.\n\nThe letter indicates that General Drakkisath guards the brand. Perhaps you should investigate.:Imbecile,\n\nI hold very little faith in your ability to prevent outsiders from accessing the master's lair. In the very likely event of your death, this orb has its own failsafe built in to prevent outsiders from teleporting directly into Blackwing.\n\nOnly those with the Mark of Drakkisath branded upon their hand may make use of this orb. Thankfully, Drakkisath is not nearly as incompetent as you, Quartermaster. He guards the brand himself!\n\n-Warchief Rend Blackhand\n\nP.S. Destroy this letter, idiot."] = {
		[1] = 7761,
	},
	["Kharan Mighthammer:59:Travel to Blackrock Depths and find Kharan Mighthammer.\n\nThe King mentioned that Kharan was being held prisoner there - perhaps you should try looking for a prison.:You have been to the smoldering ruins of Thaurissan? Did you happen to run into a pitiful lout named Kharan Mighthammer? The dwarf that was supposedly watching over my baby girl!\n\n<The King sobs.>\n\nAnd now she's gone, Fanatique!\n\nI have had my men turn the Steppes upside down. The only clue they have as to the whereabouts of my daughter is that she may be inside the Depths. For all I know, she could be dead!\n\nKharan is supposedly being held prisoner there... find him! I want answers!"] = {
		[1] = 4341,
	},
	["Kharan Mighthammer:59:Travel to Blackrock Depths and find Kharan Mighthammer.\n\nThe King mentioned that Kharan was being held prisoner there - perhaps you should try looking for a prison.:You have been to the smoldering ruins of Thaurissan? Did you happen to run into a pitiful lout named Kharan Mighthammer? The dwarf that was supposedly watching over my baby girl!\n\n<The King sobs.>\n\nAnd now she's gone, $N!\n\nI have had my men turn the Steppes upside down. The only clue they have as to the whereabouts of my daughter is that she may be inside the Depths. For all I know, she could be dead!\n\nKharan is supposedly being held prisoner there... find him! I want answers!"] = {
		[1] = 4341,
	},
	["Lawbringer's Waist:60:Trade in your current item for the item that best suits your needs.:You wear the guise of the Lawbringer, Paladin. I see it shine under the light of your faith, yet it seems rather dim. Perhaps the one you carry is not suited for the tasks you are willing to perform.\n\n<Geldra hums for a few seconds.>\n\nHand it here and tell me, by which law shall your hand be guided?"] = {
		[1] = "Lawbringer's Waist",
	},
	["Lawbringer's Wrists:60:Trade in your current item for the item that best suits your needs.:You wear the guise of the Lawbringer, Paladin. I see it shine under the light of your faith, yet it seems rather dim. Perhaps the one you carry is not suited for the tasks you are willing to perform.\n\n<Geldra hums for a few seconds.>\n\nHand it here and tell me, by which law shall your hand be guided?"] = {
		[1] = "Lawbringer's Wrists",
	},
	["Lawbringer's Feet:60:Trade in your current item for the item that best suits your needs.:You wear the guise of the Lawbringer, Paladin. I see it shine under the light of your faith, yet it seems rather dim. Perhaps the one you carry is not suited for the tasks you are willing to perform.\n\n<Geldra hums for a few seconds.>\n\nHand it here and tell me, by which law shall your hand be guided?"] = {
		[1] = "Lawbringer's Feet",
	},
	["Doomrigger's Clasp:60:Bring Doomrigger's Clasp to Mayara Brightwing in the Burning Steppes.:There is a chamber, high in Blackrock Spire, that was once called the Hall of Fortune.  It was where the Dark Iron dwarves kept their relics, trophies and objects of art.\n\nThat was long ago.  It is said the hall has collapsed and is now used for... less savory tasks.  But I believe some old dwarven relics may still be found there.\n\nOne such relic is Doomrigger's clasp, with a surface so encrusted with rare gems that it was said to make weep any dwarf who gazes upon it.\n\nThat clasp, Fanatique, is your goal."] = {
		[1] = 4764,
	},
	["Lawbringer's Legs:60:Trade in your current item for the item that best suits your needs.:You wear the guise of the Lawbringer, Paladin. I see it shine under the light of your faith, yet it seems rather dim. Perhaps the one you carry is not suited for the tasks you are willing to perform.\n\n<Geldra hums for a few seconds.>\n\nHand it here and tell me, by which law shall your hand be guided?"] = {
		[1] = "Lawbringer's Legs",
	},
	["The Madness Within:60:You must destroy the guardians surrounding the 5 Pylons that power the Prison of Immol'thar. Once the Pylons have powered down, the force field surrounding Immol'thar will have dissipated.\n\nEnter the Prison of Immol'thar and eradicate the foul demon that stands at its heart. Finally, confront Prince Tortheldrin in Athenaeum.\n\nReturn to the Shen'dralar Ancient in the courtyard should you complete this quest.:Have you heard enough? Are you a $g man:woman; of action?\n\nThis madness must come to an end. The age of the immortals has long since passed. Destroy the guardians surrounding the pylons to lower the force field. When this is done, destroy Immol'thar. With the Prince's power greatly reduced, attack and end him. Lay the spirits of this city to rest, adventurer."] = {
		[1] = 7461,
	},
	["The Last Barov:60:Travel to the Bulwark - Horde territory - and assassinate Alexi Barov. Take his head and return to Weldon Barov.\n\nBe warned, Alexi will probably be well protected by Horde filth.:With the deeds recovered, there is but one thing left to do. Alexi must be killed. With him dead, I need not ever worry about an unscrupulous gang of mercenaries seeking my head.\n\nIt's a simple task. Alexi hides under the protection of the Horde - at the Bulwark.\n\nNo, I do not expect you to just walk up and kill him, I want his head! How you get it... well, that part is up to you. That type of behavior is below one of my noble upbringing."] = {
		[1] = 5344,
	},
	["Emphasis on Sacrifice:60:Travel to Ironforge and get High Priest Rohan's Exorcism Censer.  You will need to make a donation of 150 gold in order to secure it.:In order to prepare yourself for this task, you must first show due sacrifice and judgment... with an emphasis on sacrifice.\n\nYou must acquire High Priest Rohan's exorcism censer for your task.  Even though its use will be for good and just reasons, due compensation must be given for it.\n\nProceed to Ironforge and speak with the High Priest.  By bringing ample coin with you to help offset the loss of his censer, it will show your due sacrifice.\n\nGo now Fanatique, time is of the essence."] = {
		[1] = 7637,
	},
	["The Madness Within:60:You must destroy the guardians surrounding the 5 Pylons that power the Prison of Immol'thar. Once the Pylons have powered down, the force field surrounding Immol'thar will have dissipated.\n\nEnter the Prison of Immol'thar and eradicate the foul demon that stands at its heart. Finally, confront Prince Tortheldrin in Athenaeum.\n\nReturn to the Shen'dralar Ancient in the courtyard should you complete this quest.:Have you heard enough? Are you a woman of action?\n\nThis madness must come to an end. The age of the immortals has long since passed. Destroy the guardians surrounding the pylons to lower the force field. When this is done, destroy Immol'thar. With the Prince's power greatly reduced, attack and end him. Lay the spirits of this city to rest, adventurer."] = {
		[1] = 7461,
	},
}
