
pfQuest_questcache = {
	["Victory for the Alliance:60:Take the Head of Onyxia to Highlord Bolvar Fordragon in Stormwind.:You have accomplished the impossible. The brood mother of the Black Dragonflight lies dead at your feet. Take her head and present it to the Highlord."] = {
		[1] = 7495,
	},
	["Doomrigger's Clasp:60:Bring Doomrigger's Clasp to Mayara Brightwing in the Burning Steppes.:There is a chamber, high in Blackrock Spire, that was once called the Hall of Fortune.  It was where the Dark Iron dwarves kept their relics, trophies and objects of art.\n\nThat was long ago.  It is said the hall has collapsed and is now used for... less savory tasks.  But I believe some old dwarven relics may still be found there.\n\nOne such relic is Doomrigger's clasp, with a surface so encrusted with rare gems that it was said to make weep any dwarf who gazes upon it.\n\nThat clasp, Unknown, is your goal."] = {
		[1] = 4764,
	},
	["Sweet Dreams are Made of This:24:Go to Fire Scar Shrine in Ashenvale and gather the hearts of the demons described there for Gakin the Darkbinder at the Slaughtered Lamb in Stormwind City.:Okay then, your first task for me. What, you thought I would do this for free? No, no no! Oh by fel no. In any normal circumstance I would have you killed for stumbling down here, but it just so happens, I need some materials myself, and some of these will also be required to solve your. Predicament.\n\nA connection to the void will be required, plus some sort of tonic that elicits lucid dreaming to bring forth this night-demon of yours, and banish it. My colleagues have whispered about a certain location that may just do the trick!\n\n<He smirks wickedly.>\n\nFire Scar Shrine. Name ring a bell? I doubt it. You can find it in Ashenvale, south west of Astranaar. There are foul beasts dwelling there, dog-like, ravenous and demonic. I need you to go there, kill them, and bring me their hearts. I will need one for you, but I never, ever work for free. Make it ten."] = {
		[1] = 40569,
	},
	["The Long Night Is Not Over:60:Bring 1 Argent Dawn Valor Token to Miranda Breechlock in Light's Hope Chape.:Tales of your victories against the scourge raise the spirits of the downtrodden and give hope for a better tomorrow.\n\nBut for all your efforts, our enemies yet shamble in the dark and cast a pall over the land. The long night is yet to be over.\n\nWe mustn't relent!\n\nBy the Light, we must keep on, and bring salvation to those the Scourge would seek to harm. Prove that your mettle remains as sharp as steel.\n\nBring me an Argent Dawn Valor Token, and in exchange, I will grant you a boon to aid in your battles against the undead."] = {
		[1] = 40221,
	},
	["The Lord of Blackrock:60:Venture to the Valley of Heroes in Stormwind City and speak with Field Marshal Afrasiabi.:Go to the Valley of Heroes and speak with Field Marshal Afrasiabi."] = {
		[1] = 7782,
	},
	["Spectral Wine:60:Gather 3 Essence of Death, 5 Flask of Port, and a Ghost Mushroom for The Cook in Karazhan.:Believe it or not, I do have a recipe for Spectral Wine. Wine that can be consumed by spirits was a concept that I did practice and refine. It is a somewhat complicated process and requires materials that are foreign here in Karazhan.\n\nIf you can acquire for me three Essences of Death, five Flasks of Port, and a single Ghost Mushroom, I can make Spectral Wine for Councilman Kyleson. Though, I must question your sanity in going to this trouble."] = {
		[1] = 41085,
	},
	["The Key to Karazhan IV:60:Ask Magus Hallister in Theramore for the whereabouts of Vandol.:Yes, yes, Archmage Vandol was truly one of the greatest minds of the Kirin Tor. He was a dear friend of Medivh, if you can believe such a thing. Although, some might argue that Medivh had no true friends.\n\nAlas, I fear I cannot be of much assistance to you. After the devastation of Dalaran at the hands of Archimonde, Vandol suffered injuries that took a great toll on him. He spent many moons in recovery and eventually retired as one of the most accomplished mages of our time.\n\nI seem to recall him expressing a desire to settle in or around Theramore. If he still lives, I suggest asking for him in the city itself. One of our apprentices, Magus Halister, might know of his whereabouts."] = {
		[1] = 41136,
	},
	["Report to Marshal Bluewall:60:Speak with Marshal Bluewall at the Alliance encampment near Hive'Zora.:Are you Marshal Bluewall's new recruits? Of course you are.\n\nWhat are you waiting for? Good soldiers are dying in the desert. Aren't you excited to join them?\n\nNow, get going and don't dry out on the way."] = {
		[1] = 9415,
	},
	["Elven Legends:60:Search Dire Maul for Kariel Winthalus. Report back to Scholar Runethorn at Feathermoon with whatever information that you may find.:Several years ago, a lone elven master named Kariel Winthalus fled the devastation of his homeland with several ancient elven artifacts in tow.\n\nOur search for this lost master lead us from the ruins of Quel'Thalas, through the Burning Steppes, across the great expanses of the sea, to Feralas.\n\nWe suspect that the elf sought sanctuary in the halls of Eldre'Thalas (what is now known as Dire Maul).\n\nYou must find him, adventurer. Whether alive or dead, the knowledge he carried must be recovered!"] = {
		[1] = 7482,
	},
	["The Lord of Blackrock:60:Return the Head of Nefarian to Highlord Bolvar Fordragon in Stormwind.:The old feeling returns. The welcome pangs of victory reverberate throughout your being. Before you lies the monolithic, battle scarred head of Nefarian. Return it to your Highlord, champion."] = {
		[1] = 7781,
	},
	["Cryptstalker Armor Doesn't Make Itself...:60:Huntsman Leopold at Light's Hope Chapel in the Eastern Plaguelands wants 30 Crypt Fiend Parts.:How would you like to earn yourself one of these shiny coins?\n\n<Leopold holds up an insignia of the Crusade.>\n\nI've got a little problem that you might be able to help me with, Fanatique. You see, I make Cryptstalker armor for those daft enough to venture into Naxxramas. While they supply me with the core material requirements for the armor, I always run out of the crypt fiend parts. Bring me back a bundle of parts and I'll pay you with an insignia - usable at the quartermaster."] = {
		[1] = 9124,
	},
	["The Key to Karazhan III:60:Find someone from the Kirin Tor who might know something about Vandol. Dalaran could be a good place to start your search.:I sense that you possess Medivh's key. Though I am unsure how you came into its possession, I must warn you: not all is what it seems, and the powers residing in Upper Chambers are beyond your comprehension.\n\nWhen Medivh was younger, he often hosted a certain Kirin Tor mage in the tower. His name was Vandol, and if anyone could be able to repair the key, it's him.\n\nMake haste, for there are ominous noises emanating from the Upper Chambers, and I fear that the situation there will only become worse."] = {
		[1] = 40819,
	},
	["The Key to Karazhan VIII:60:Slay Immol'thar in Dire Maul, retrieve gems from his skin, and return to Vandol.:<Dolvan carefully examines the key, studying it from every angle and reciting incantations to detect any potential issues.>\n\nIt appears that there is an interruption in the flow of arcane energy through the key. Upon further inspection, I have discovered that the crystals that hold the key together have been damaged beyond repair. Unfortunately, I do not possess the skills to fix them, and we will need to obtain new crystals to restore the key's functionality.\n\nI have heard rumors of a demon named Immol'thar who resides deep within the dungeons of Dire Maul. According to legend, his skin is adorned with peculiar gems that could potentially be used to repair the key. However, be warned that Immol'thar is a formidable foe, and the journey to reach him will not be easy."] = {
		[1] = 40827,
	},
	["Cenarion Battlegear:60:Talk to Vargus at Cenarion Hold in Silithus.:As you complete the tasks you're assigned in the war you'll want to talk to Vargus, the blacksmith.  Show him any badges you've earned along the way. He'll provide you with gear to match your level of commitment to our cause."] = {
		[1] = 8800,
	},
	["The Binding of Xanthar:60:Gather the Upper Binding of Xanthar and the Lower Binding of Xanthar for Hanvar the Righteous in the small church outside of Karazhan.:Some years ago, a rare and powerful item was stored inside of this church. I have been cursed to remain ever since its disappearance years ago. If you could recover this item and return it to Karazhan, I would be more than thankful.\n\nThe Binding was torn apart before it was ever stolen, both halves now rest with separate owners. The first was taken by a hermit mage who held no affiliations, his accent certainly sounded like he came from the north.\n\nThe second half of the binding was taken by a man of faith, of vigilance, wearing red cloth and bearing the symbol of the Light itself. His ravings almost sounded mad!\n\nGather me both the upper and lower half of the binding, and I can make it whole."] = {
		[1] = 41015,
	},
	["Drakefire Amulet:60:You must retrieve the Blood of the Black Dragon Champion from General Drakkisath. Drakkisath can be found in his throne room behind the Halls of Ascension in Blackrock Spire.:It is a piece of the dragon; a scale - enchanted and transformed. Whole, it could have granted access to the beast's lair. Shattered, it is useless.\n\nIt is possible to repair the item, but to do so would require the blood of a black dragon champion. There is one... He is known as General Drakkisath, ruler of the dragonspawn armies of Nefarian. Perhaps you have heard of him?\n\nReturn with his blood, human, and I shall enchant the fragment into something that will grant you access to Onyxia's lair."] = {
		[1] = 6502,
	},
	["The Madness Within:60:You must destroy the guardians surrounding the 5 Pylons that power the Prison of Immol'thar. Once the Pylons have powered down, the force field surrounding Immol'thar will have dissipated.\n\nEnter the Prison of Immol'thar and eradicate the foul demon that stands at its heart. Finally, confront Prince Tortheldrin in Athenaeum.\n\nReturn to the Shen'dralar Ancient in the courtyard should you complete this quest.:Have you heard enough? Are you a woman of action?\n\nThis madness must come to an end. The age of the immortals has long since passed. Destroy the guardians surrounding the pylons to lower the force field. When this is done, destroy Immol'thar. With the Prince's power greatly reduced, attack and end him. Lay the spirits of this city to rest, adventurer."] = {
		[1] = 7461,
	},
	["Secrets of the Qiraji:60:Take the Ancient Qiraji Artifact to the dragons hiding near the entrance of the temple.\n:You have discovered an ancient Qiraji artifact! Perhaps one of the dragons near the entrance of the temple would have a use for this relic."] = {
		[1] = 8784,
	},
	["The Active Agent:60:Travel to Stratholme and search the ziggurats. Find and return new Scourge Data to Betina Bigglezink.\n:You will have to delve deeper into Stratholme, Fanatique.\n\nBeyond the first gates you will find the ziggurats. We know that the Scourge draws great power from these structures. Search the Ziggurats and return with any information that you may discover.\n"] = {
		[1] = 5213,
	},
	["Ring of Eternal Justice:60:Bring 1 Qiraji Magisterial Ring, 2 Vermillion Idols, 5 Silver Scarabs and 5 Bone Scarabs to Windcaller Yessendra  in Silithus.  You must also attain Honored reputation with Cenarion Circle to complete this quest.:The rings worn by the Qiraji lieutenants are rumored to grant them formidable abilities.  The corrupted gems that adorn them could, in theory, be swapped out with more pure materials to create uncorrupted versions of the rings.\n\nThe gems that adorn Qiraji idols would work quite well, as their quality is superior.\n\nBring me the ring and idols and I'll create a powerful ring for you, $c."] = {
		[1] = 8703,
	},
	["Avenger's Crown:60:Bring Vek'lor's Diadem, 2 Idols of Rebirth, 5 Stone Scarabs and 5 Crystal Scarabs to Andorgos in Ahn'Qiraj.  You must also attain Friendly reputation with the Brood of Nozdormu to complete this quest.:The Twin Emperors... their incessant whispers are slowly taking a toll on my sanity.  They mock me, knowing I cannot step further into their domain to save my brother Arygos.\n\nIn my visions I see their monstrous faces adorned by powerful crowns.  But I will have my revenge... I will transmute these symbols of Qiraji power to ones better suited to our needs.\n\nBring me the components I require, $N.  I will give you a headpiece of unmatched power."] = {
		[1] = 8628,
	},
	["Binding the Dreadnaught:60:Korfax at Light's Hope Chapel in the Eastern Plaguelands wants 30 Dark Iron Scraps.:Have you ever seen Dreadnaught armor, paladin? No, of course you haven't. You're still a girl - a tyke. Let me tell you, it is glorious.\n\nYou're probably asking yourself what any of this has to do with you, right? I'll tell you what, scrub; I need Dark Iron scraps and I'm willing to pay to get my hands on as many as possible.\n\nI need the scraps to put together sets of Dreadnaught for our champions. Bring me scraps and get paid."] = {
		[1] = 9131,
	},
	["The Key to Karazhan II:60:Kill Moroes and retrieve the Key to the Upper Chambers. Moroes resides in Lower Karazhan Halls. Bring back the key to Lord Ebonlocke.:Ah, so you have made the decision to seek the forbidden knowledge of Karazhan. I cannot blame you, for the allure of such power and secrets can be irresistible to even the most noble of intentions. Perhaps you seek this knowledge in the hopes of using it for the greater good of this world, and for that, I commend you.\n\nIf you truly wish to unlock the secrets of the Upper Chambers, you must first find Moroes, the cursed and undead castellan who guards the key to the forbidden section of the tower. It will not be an easy task, for he is cunning and fiercely protective of the secrets he guards. Be wary, as I do not know who the true master of Moroes is.\n\nBut if you can overcome his defenses and obtain the key, you may be able to enter the Upper Chambers and uncover the knowledge you seek."] = {
		[1] = 40818,
	},
	["The Madness Within:60:You must destroy the guardians surrounding the 5 Pylons that power the Prison of Immol'thar. Once the Pylons have powered down, the force field surrounding Immol'thar will have dissipated.\n\nEnter the Prison of Immol'thar and eradicate the foul demon that stands at its heart. Finally, confront Prince Tortheldrin in Athenaeum.\n\nReturn to the Shen'dralar Ancient in the courtyard should you complete this quest.:Have you heard enough? Are you a $g man:woman; of action?\n\nThis madness must come to an end. The age of the immortals has long since passed. Destroy the guardians surrounding the pylons to lower the force field. When this is done, destroy Immol'thar. With the Prince's power greatly reduced, attack and end him. Lay the spirits of this city to rest, adventurer."] = {
		[1] = 7461,
	},
	["Judgement's Shoulders:60:Trade in your current item for the item that best suits your needs.:You wear the guise of Judgment, Paladin. I see it shine under the light of your faith, yet it seems rather dim. Perhaps the one you carry is not suited for the tasks you are willing to perform.\n\n<Geldra hums for a few seconds.>\n\nHand it here and tell me, what sins do you seek to judge?"] = {
		[1] = "Judgement's Shoulders",
	},
	["Drakefire Amulet:60:You must retrieve the Blood of the Black Dragon Champion from General Drakkisath. Drakkisath can be found in his throne room behind the Halls of Ascension in Blackrock Spire.:It is a piece of the dragon; a scale - enchanted and transformed. Whole, it could have granted access to the beast's lair. Shattered, it is useless.\n\nIt is possible to repair the item, but to do so would require the blood of a black dragon champion. There is one... He is known as General Drakkisath, ruler of the dragonspawn armies of Nefarian. Perhaps you have heard of him?\n\nReturn with his blood, $r, and I shall enchant the fragment into something that will grant you access to Onyxia's lair."] = {
		[1] = 6502,
	},
	["The Last Barov:60:Travel to the Bulwark - Horde territory - and assassinate Alexi Barov. Take his head and return to Weldon Barov.\n\nBe warned, Alexi will probably be well protected by Horde filth.:With the deeds recovered, there is but one thing left to do. Alexi must be killed. With him dead, I need not ever worry about an unscrupulous gang of mercenaries seeking my head.\n\nIt's a simple task. Alexi hides under the protection of the Horde - at the Bulwark.\n\nNo, I do not expect you to just walk up and kill him, I want his head! How you get it... well, that part is up to you. That type of behavior is below one of my noble upbringing."] = {
		[1] = 5344,
	},
	["Emphasis on Sacrifice:60:Travel to Ironforge and get High Priest Rohan's Exorcism Censer.  You will need to make a donation of 150 gold in order to secure it.:In order to prepare yourself for this task, you must first show due sacrifice and judgment... with an emphasis on sacrifice.\n\nYou must acquire High Priest Rohan's exorcism censer for your task.  Even though its use will be for good and just reasons, due compensation must be given for it.\n\nProceed to Ironforge and speak with the High Priest.  By bringing ample coin with you to help offset the loss of his censer, it will show your due sacrifice.\n\nGo now Fanatique, time is of the essence."] = {
		[1] = 7637,
	},
	["The Sigil of Quickness:60:Gather 5 Bright Dream Shards and a Fading Dream Fragment for Vaenar Hollowstar at Nordanaar in Hyjal:The Sigil of Quickness is infused with the powers of speed. Upon using its energy, you will find yourself able to strike at a quicker pace.\n\nIf you desire this sigil, I will require five Bright Dream Shards. I will also require a Fading Dream Fragment. I cannot just give it away without proof of your deeds here in Hyjal."] = {
		[1] = 40910,
	},
	["Strange Bedfellows:25:Find a way to summon the demon, slay it, and bring its heart to Bert Mano.:This is it. If you have any friends who can work discreetly, I suggest you contact them now.\n\nThe energy will be strongest either around Bert himself or where he sleeps. Hold out the pendant and see if it reacts. Hopefully, this will give you the opportunity to confront this demon and put an end to the torment.\n\nYou should probably take some evidence of its existence once you kill it, too, you know. So he can prove his situation and resolve the troubles with his fiance."] = {
		[1] = 40571,
	},
	["The Key to Karazhan IX:60:Find \"Treatise on Magical Locks and Keys\" and bring it back to Vandol. It is rumored to be kept in Blackwing Lair.:<Dolvan labors over the key, his expression contorting with disappointment as time passes.>\n\nI cannot comprehend. This does not work. I believed I was well-versed in the sorcery of Medivh, but alas, I have been proven wrong. This man possessed great talent, if only...\n\nBut I digress. We must repair the key, and there remains one final possibility that comes to mind.\n\nI require a rare tome, penned in times long past by Aegwynn, entitled \"Treatise on Magical Locks and Keys\". It has been lost since the destruction of Dalaran, but whispers suggest it is now held by none other than Lord Victor Nefarius...\n\nThis is our only chance. Retrieve the tome."] = {
		[1] = 40828,
	},
	["Blackhand's Command:60:That is one stupid orc. It would appear as if you need to find this brand and gain the Mark of Drakkisath in order to access the Orb of Command.\n\nThe letter indicates that General Drakkisath guards the brand. Perhaps you should investigate.:Imbecile,\n\nI hold very little faith in your ability to prevent outsiders from accessing the master's lair. In the very likely event of your death, this orb has its own failsafe built in to prevent outsiders from teleporting directly into Blackwing.\n\nOnly those with the Mark of Drakkisath branded upon their hand may make use of this orb. Thankfully, Drakkisath is not nearly as incompetent as you, Quartermaster. He guards the brand himself!\n\n-Warchief Rend Blackhand\n\nP.S. Destroy this letter, idiot."] = {
		[1] = 7761,
	},
	["Ring of Eternal Justice:60:Bring 1 Qiraji Magisterial Ring, 2 Vermillion Idols, 5 Silver Scarabs and 5 Bone Scarabs to Windcaller Yessendra  in Silithus.  You must also attain Honored reputation with Cenarion Circle to complete this quest.:The rings worn by the Qiraji lieutenants are rumored to grant them formidable abilities.  The corrupted gems that adorn them could, in theory, be swapped out with more pure materials to create uncorrupted versions of the rings.\n\nThe gems that adorn Qiraji idols would work quite well, as their quality is superior.\n\nBring me the ring and idols and I'll create a powerful ring for you, paladin."] = {
		[1] = 8703,
	},
	["Avenger's Legguards:60:Bring the Skin of the Great Sandworm, 2 Idols of Strife, 5 Bronze Scarabs and 5 Ivory Scarabs to Kandrostrasz inside Ahn'Qiraj. You must also attain Friendly reputation with the Brood of Nozdormu to complete this quest.:You seek to prove your worth to my kind, mortal?  Very well, perhaps we can be of mutual assistance.\n\nThe ancient sandworm, Ouro, is a being of legendary power.  He is rumored to have been created by the Old God himself as a mockery of life.\n\nHis skin is unnatural... thick, nearly impregnable, yet it's flexible and allows him to move with the speed and grace of a much smaller creature.\n\nBring me a sample of his skin along with other minor components and I shall craft you leggings of great power."] = {
		[1] = 8629,
	},
	["Suitable Accomodations:60:Find a Comfortable Pillow for Councilman Kyleson in Karazhan.:You there, servant!\n\nI must say, the room service you have here is utterly dreadful. I feel like I have been waiting years for someone to come along and help me with my problem.\n\nThe chambers I have been assigned are not suitable, and I cannot get a wink of sleep. I need a more comfortable pillow, or something of that regard. Find one for me so that I may actually get a good night's rest in this place."] = {
		[1] = 41083,
	},
	["Libram of Rapidity:60:Bring a Libram of Rapidity, 1 Pristine Black Diamond, 2 Large Brilliant Shards, and 2 Blood of Heroes to Lorekeeper Lydros in Dire Maul to receive an Arcanum of Rapidity.:Master Winthalus lost the Libram of Rapidity in the east wing. The Libram will allow for a minor haste cantrip to be placed upon your equipment. Parlor tricks, really...\n\nRegardless, if you are interested, you will need to present the Libram along with some basic reagents.\n\nHrm... I believe it also requires blood of heroes, a pristine black diamond, and large brilliant shards. I could be wrong!\n\n<Lydros shrugs.>"] = {
		[1] = 7483,
	},
	["Dragonkin Menace:54:Slay 15 Black Broodlings, 10 Black Dragonspawn, 4 Black Wyrmkin and 1 Black Drake. Return to Helendis Riverhorn when the task is complete.:Life in the Burning Steppes is rife with conflict.\n\nJust look at this place! We know very little of what happened to these buildings, but we do know that at one time, before the great explosion, this was all part of the Redridge mountain range.\n\nEnough lamenting! We have a problem, Fanatique. You may have noticed the dragonkin below this ridge. We need assistance in pushing them back. Kill as many as you can and return to me. Succeed and perhaps we can talk of other things.\n"] = {
		[1] = 4182,
	},
	["The Dragon's Eye:60:You must search the world for a being capable of restoring the power to the Fragment of the Dragon's Eye. The only information you possess about such a being is that they exist.:A fragment of the shattered medallion is all that I can offer.\n\nYou must find another of dragon blood willing to assist you in forging a new key. Once you secure this key, you must travel to the Wyrmbog in Dustwallow Marsh. It is there that you will find her lair, Fanatique.\n\nWhere to find other flights willing to help? Sadly, I do not know... They are said to exist. Some may even work and live among us, disguised as one of the humanoid races. I wish you luck.\n"] = {
		[1] = 6501,
	},
	["Emphasis on Sacrifice:60:Travel to Ironforge and get High Priest Rohan's Exorcism Censer.  You will need to make a donation of 150 gold in order to secure it.:In order to prepare yourself for this task, you must first show due sacrifice and judgment... with an emphasis on sacrifice.\n\nYou must acquire High Priest Rohan's exorcism censer for your task.  Even though its use will be for good and just reasons, due compensation must be given for it.\n\nProceed to Ironforge and speak with the High Priest.  By bringing ample coin with you to help offset the loss of his censer, it will show your due sacrifice.\n\nGo now Unknown, time is of the essence."] = {
		[1] = 7637,
	},
	["Celebrating Good Times:60:Seek out Major Mattingly in the Valley of Heroes.:Seek out Major Mattingly in the Valley of Heroes, Fanatique. He will be expecting you..."] = {
		[1] = 7496,
	},
	["Echoes of War:60:Commander Eligor Dawnbringer at Light's Hope Chapel in the Eastern Plaguelands wants you to slay 5 Living Monstrosities, 5 Stoneskin Gargoyles, 8 Deathknight Captains and 3 Venom Stalkers.:Five years since the last war...\n\nTens of thousands of lives were lost and for what? The threat was never fully extinguished.\n\nAnd so the Lich King stirs once more... His yes-man, Kel'Thuzad, amassing for another attack upon our lands.\n\nWe will not allow it! Prove your dedication. Prove that you are willing to risk life and limb to stop this madness and the combined might of the Dawn and the Crusade will be at your beck and call.\n\nEnter Naxxramas and destroy the Scourge within..."] = {
		[1] = 9033,
	},
	["Lawbringer's Hands:60:Trade in your current item for the item that best suits your needs.:You wear the guise of the Lawbringer, Paladin. I see it shine under the light of your faith, yet it seems rather dim. Perhaps the one you carry is not suited for the tasks you are willing to perform.\n\n<Geldra hums for a few seconds.>\n\nHand it here and tell me, by which law shall your hand be guided?"] = {
		[1] = "Lawbringer's Hands",
	},
	["Lawbringer's Wrists:60:Trade in your current item for the item that best suits your needs.:You wear the guise of the Lawbringer, Paladin. I see it shine under the light of your faith, yet it seems rather dim. Perhaps the one you carry is not suited for the tasks you are willing to perform.\n\n<Geldra hums for a few seconds.>\n\nHand it here and tell me, by which law shall your hand be guided?"] = {
		[1] = "Lawbringer's Wrists",
	},
	["A Drink to Sleep:60:Speak with someone who may know how to acquire wine for Councilman Kyleson.:You've been a wonderful help in acquiring this, but I need one last thing before I can get some rest. Fetch for me a glass of wine, the best that you have. I am certain that you know exactly what I am talking about. Go on now, and find what I'm looking for so I can get some sleep."] = {
		[1] = 41084,
	},
	["Kharan Mighthammer:59:Travel to Blackrock Depths and find Kharan Mighthammer.\n\nThe King mentioned that Kharan was being held prisoner there - perhaps you should try looking for a prison.:You have been to the smoldering ruins of Thaurissan? Did you happen to run into a pitiful lout named Kharan Mighthammer? The dwarf that was supposedly watching over my baby girl!\n\n<The King sobs.>\n\nAnd now she's gone, $N!\n\nI have had my men turn the Steppes upside down. The only clue they have as to the whereabouts of my daughter is that she may be inside the Depths. For all I know, she could be dead!\n\nKharan is supposedly being held prisoner there... find him! I want answers!"] = {
		[1] = 4341,
	},
	["The Human, Ras Frostwhisper:60:Travel to the Arathi Highlands, to the ruins of Stromgarde. Search Stromgarde for a Keepsake of Remembrance. If you find such an item, return with it to Magistrate Marduke.:The undead fear life just as the living fear death. It is not unusual for a sentient undead being to completely destroy all remnants of his or her previous life after having turned.\n\nUnfortunately, in order to create an artifact capable of reverting Ras Frostwhisper to a mortal, we must have a keepsake from his years among the living.\n\nYou must venture to the ruined city of Stromgarde, Frostwhisper's home, and search for such an item. May luck be with you, Fanatique."] = {
		[1] = 5461,
	},
	["The Key to Karazhan VII:60:Find four Echoes of Medivh. They might be found in places of great significance for the mage. Then return to Dolvan with the key.:Regrettably, my knowledge of the whereabouts of Medivh's Echoes is limited. To begin your search, I suggest visiting the locations that Medivh frequented during his second life, when he returned to redeem himself and prepare for the impending Third War. These events are relatively recent, so the Echoes should be easier to locate and more potent.\n\nIt is likely that the Echoes of Medivh's presence will be accompanied by objects that once belonged to him. Perhaps a stray feather from his cloak, or some other memento that carries his essence.\n\nHowever, time is of the essence, and you must act quickly. Go forth and begin your search for at least four of his Echoes. I believe this should be enough to recharge the key and unlock the chambers of Karazhan."] = {
		[1] = 40826,
	},
	["Aurel Goldleaf:60:Speak with Aurel Goldleaf in Cenarion Hold.:Fanatique, although we had hoped the Twilight's Hammer's operations in Silithus were slowing... we were, regrettably, mistaken.  Through continued forays against the cult, we have learned that an even darker power, the Abyssal Council, controls the Hammer through the arcane wind stones dotted amongst the cult's camps.  Your next action, Fanatique, will be against the Abyssal Council.\n\nSpeak with the craftsman Aurel Goldleaf, in the eastern section of Cenarion Hold.  Her skill will be needed for this next gambit."] = {
		[1] = 8331,
	},
	["Avenger's Crown:60:Bring Vek'lor's Diadem, 2 Idols of Rebirth, 5 Stone Scarabs and 5 Crystal Scarabs to Andorgos in Ahn'Qiraj.  You must also attain Friendly reputation with the Brood of Nozdormu to complete this quest.:The Twin Emperors... their incessant whispers are slowly taking a toll on my sanity.  They mock me, knowing I cannot step further into their domain to save my brother Arygos.\n\nIn my visions I see their monstrous faces adorned by powerful crowns.  But I will have my revenge... I will transmute these symbols of Qiraji power to ones better suited to our needs.\n\nBring me the components I require, Unknown.  I will give you a headpiece of unmatched power."] = {
		[1] = 8628,
	},
	["The Key to Karazhan VI:60:Listen to Vandol's story.:So, you come seeking my help to repair the key to the Upper Chambers of Karazhan. It seems my past association with Medivh has once again come back to haunt me, but I suppose that's the price I must pay.\n\nMedivh himself knew the risks of what he was doing, but his insatiable thirst for knowledge and power blinded him to the consequences of his actions.\n\nWe must proceed with caution. Are you prepared to face the dangers that await, knowing that the powers you seek may be too great for you to handle?\n\nStay awhile and listen."] = {
		[1] = 40825,
	},
	["Gurubashi, Vilebranch, and Witherbark Coins:60::I seek the Paragons of Power known as the Coins of the Tribes.  They are the currency used by the various denizens of Zul'Gurub, and each is imbued with subtle but powerful mojo.\n\nThere are nine distinct kinds to be found.  Some are sought after by my compatriots for various armors they offer Zandalar heroes.  Should you have any extra, I will trade you one of our Honor Tokens for a set of three.  You may use the Tokens with Rin'wosho the Trader; he offers our heroes special items for them."] = {
		[1] = 8238,
	},
	["Only One May Rise:60:Return the Head of the Broodlord Lashlayer to Baristolth of the Shifting Sands at Cenarion Hold in Silithus.:There is no time to waste! A hero must be found! The task I give will require an army to complete but only one may rise from the throng of would be champions to take on the burden and responsibility of an ally of the Brood.\n\nWithin the lair of the Lord of Blackrock is a most cruel beast. The Broodlord Lashlayer guards the Halls of Strife, blocking the way into Nefarian's inner sanctum. Slay the foul aberration and return his head to me. Do this and you may begin the next step of your journey."] = {
		[1] = 8288,
	},
	["Bonescythe Digs:60:Rohan the Assassin at Light's Hope Chapel in the Eastern Plaguelands wants 30 Bone Fragments.\n:Don Julio's Bonescythe armor pattern requires bone fragments - a lot of bone fragments. While those crazy enough to venture into Naxxramas provide me with enough of the core materials to make the armor, I'm always looking for more Scourge bone fragments.\n\nSo what do you think? Interested in getting your hands dirty and destroying some Scourge at the same time? It's a win-win situation."] = {
		[1] = 9126,
	},
	["The Treasure of the Shen'dralar:60:Return to the Athenaeum and find the Treasure of the Shen'dralar. Claim your reward!:In the library, Athenaeum, you will find an ancient chest hidden beneath the stairway. Take from it that which you desire."] = {
		[1] = 7462,
	},
	["The Mystery of Karazhan I:60:Search for the Pendant of Ardan, rumored to be held by the ogre Var'zhog, collect it, and return to Magus Ariden Dusktower in Deadwind Pass.:I have ventured to this rather decrepid, and lonely place to investigate the mysteries surrounding Karazhan. It has long since loomed over this land with a great power emitting from it. While the tower is impressive, it does not boast the power it once held under the rule of Medivh.\n\nMy analysis of the tower is that the growing power does not come from above, but below. There have always been tales of a crypt that stretched deep beneath Karazhan, perhaps they may be true.\n\nThe first thing I ask of you is to search for a long lost pendant, rumored to have been taken from the ruins of Karazhan some time ago. It will be needed to magically attune the key for our purposes. My suspicion is that the ogre's of the region have taken hold of it. An ogre magi by the name of Var'zhog has grown to some renown as of recently, no doubt he holds the pendant."] = {
		[1] = 40311,
	},
	["Smelting Dreamsteel:60:Gather 15 Bright Dream Shards for Tanthos Everbreeze at Nordanaar in Hyjal.:The ability to smelt Dreamsteel is an art all in itself. Whilst the difficulty to actually create patterns using Dreamsteel Bars is complicated, it does not overshadow the smelting process.\n\nIf you wish to learn how to create your own Dreamsteel Bars and not rely on others, gather for me fifteen Bright Dream Shards as a showing of your loyalty to the World Tree."] = {
		[1] = 40886,
	},
	["The Key to Karazhan I:60:Listen to the story of Lord Ebonlocke.:The Living? Here? I never thought I would see the day.\n\nMy cursed spirit is forever bound here, unable to find the sweet release of true death. The memories of my past still haunt me, a never-ending reminder of the consequences of my actions.\n\nYet, here you stand, wandering through these halls, oblivious to the horrors that await you. Stay for a while and listen to my story, if it is the mysteries of Karazhan you seek to unravel. But be warned, for there are darker secrets buried within these walls that even I am not privy to.\n\nIf you are determined enough to delve into the enigmas of Medivh's tower, perhaps the true purpose of this accursed place will reveal itself. Or perhaps you will simply become lost to the madness that has ensnared so many others before you. A tormented spectre of the past, forever trapped within these walls, just like me..."] = {
		[1] = 40817,
	},
	["The Active Agent:60:Travel to Stratholme and search the ziggurats. Find and return new Scourge Data to Betina Bigglezink.\n:You will have to delve deeper into Stratholme, Unknown.\n\nBeyond the first gates you will find the ziggurats. We know that the Scourge draws great power from these structures. Search the Ziggurats and return with any information that you may discover.\n"] = {
		[1] = 5213,
	},
	["Paragons of Power: The Freethinker's Belt:61:Bring Jin'rokh the Breaker a Primal Hakkari Shawl.  You must also have a reputation equal to or greater than Honored with the Zandalar Tribe.\n\nJin'rokh the Breaker is located on Yojamba Isle, Stranglethorn Vale.:Your beliefs are alien to us, heathen.  Ancient Zandalar were once branded as heretics.  This was when the Gurubashi Empire was strong.  Heathens dared to challenge the priest of Hakkar.  Heathens then were hunted and killed as vermin.  Those heathens never wavered in their fight against the Blood God.  We honor the price they paid.  They are the freethinkers.\n\nDestroy the minions of Hakkar in Zul'Gurub.  Bring me the Paragons of Power I seek.  Success will be greatly rewarded.\n\nGo."] = {
		[1] = 8054,
	},
	["The Elemental Equation:60:Archmage Angela Dosantos at Light's Hope Chapel in the Eastern Plaguelands wants 30 Core of Elements.\n:Greetings, adventurer! Are you interested in some work? I pay those under my employ with insignias. These insignias can be used at the Quartermaster to purchase items of power.\n\nAll I need you to do is bring me as many core of elements as you can carry. The more the better!\n\nYou'll find them on elementals of varying shapes and sizes that exist across our world."] = {
		[1] = 9128,
	},
	["Judgement's Feet:60:Trade in your current item for the item that best suits your needs.:You wear the guise of Judgment, Paladin. I see it shine under the light of your faith, yet it seems rather dim. Perhaps the one you carry is not suited for the tasks you are willing to perform.\n\n<Geldra hums for a few seconds.>\n\nHand it here and tell me, what sins do you seek to judge?"] = {
		[1] = "Judgement's Feet",
	},
	["Dangerous Love:60:Get a Stormwind Guard's Card and return it to Aristan Mottar in Stormwind.:There's something unnatural about this epidemic of love. It's not proper, it's an eyesore, and at worst, it could be a threat to the the safety of the Alliance itself.\n\nJust think: what if the guards have been taken in by this strange affliction? Something must be done.\n\nGo to one of the guards here in Stormwind and see if they've been caught up in this foolishness."] = {
		[1] = 8903,
	},
	["What Tomorrow Brings:60:Venture to the Caverns of Time in Tanaris and find Anachronos, Brood of Nozdormu.:The embrace of death had all but overcome my being when he intervened. He breathed only once upon my maimed body and then waited patiently for the sands of time to cleanse my wounds.\n\n\"Forever you will remain if you must,\" he said, and with those words I was bound as a Watcher.\n\nLook now to the desert. The second war is upon us. You must seek out the resting place of the Bronze. Venture to the Caverns of Time and see if the master has returned. I must be sure before I am able to proceed."] = {
		[1] = 8286,
	},
	["Lawbringer's Legs:60:Trade in your current item for the item that best suits your needs.:You wear the guise of the Lawbringer, Paladin. I see it shine under the light of your faith, yet it seems rather dim. Perhaps the one you carry is not suited for the tasks you are willing to perform.\n\n<Geldra hums for a few seconds.>\n\nHand it here and tell me, by which law shall your hand be guided?"] = {
		[1] = "Lawbringer's Legs",
	},
	["Savage Flora:60:Rayne at Light's Hope Chapel in the Eastern Plaguelands wants 30 Savage Fronds.:I make a special type of armor for the brave heroes that enter Naxxramas known as Dreamwalker. They are able to provide me with most of the materials I require but I am always looking for those able to retrieve savage fronds from the flora of our world.\n\nYou may think of this job as beneath you, but without the fronds, the armor could not be made.\n\nI am also in a unique position to pay you with an insignia of your choice as both the Dawn and the Crusade supply me with funds.\n"] = {
		[1] = 9136,
	},
	["Earlwake No More:60:The lead runs dry, Archibald is of no help. But perhaps the description of the orc he provided can aid in the search for Tillia's necklace. :Yer looking for the Earlwake Estate? Don't make me laugh, that wretched place is nothing but a memory, burned to the ground years ago, and all my dreams and hopes with it. What ya see before ya is all that's left of the Earlwake name - this pathetic, worthless pile of failures. \n\n<A guttural burp escapes him and vomit follows suit, dripping unto his already dirty shirt.>\n\nWe lost everything, everything! They looted our treasury and murdered anyone inside the house. Even... even my beloved Georgina... Seeing her lie there, lifeless... the diamond necklace I stole for her, still shining... That beast, that orc ripped it from her - I may be blind but I can still see it... in my head! How he laughed and worshipped his warchief, that Doomhammer! I will never forget that monster, ever! Had it been me, I would've slaughtered them all, not put them into camps!\n\nWhatever ya want from me, I don't have it, stop asking me questions! Piss off and leave me be!"] = {
		[1] = "Earlwake No More",
	},
	["Shard Harmonization:60::"] = {
		[1] = 40813,
	},
	["Kharan Mighthammer:59:Travel to Blackrock Depths and find Kharan Mighthammer.\n\nThe King mentioned that Kharan was being held prisoner there - perhaps you should try looking for a prison.:You have been to the smoldering ruins of Thaurissan? Did you happen to run into a pitiful lout named Kharan Mighthammer? The dwarf that was supposedly watching over my baby girl!\n\n<The King sobs.>\n\nAnd now she's gone, Fanatique!\n\nI have had my men turn the Steppes upside down. The only clue they have as to the whereabouts of my daughter is that she may be inside the Depths. For all I know, she could be dead!\n\nKharan is supposedly being held prisoner there... find him! I want answers!"] = {
		[1] = 4341,
	},
	["Back to Reality:24:Bring the Felbound Pendant to Marge Blackwood at Hawk's Vigil in Wetlands.:You know what? You've actually impressed me, human. I will consider your payment complete. Take this pendant back with you. It has a powerful tether which will draw demonic energies into our world. Needless to say it is HIGHLY forbidden, so do not show it to anyone but the one who sent you here."] = {
		[1] = 40570,
	},
	["The Active Agent:60:Travel to Stratholme and search the ziggurats. Find and return new Scourge Data to Betina Bigglezink.\n:You will have to delve deeper into Stratholme, $N.\n\nBeyond the first gates you will find the ziggurats. We know that the Scourge draws great power from these structures. Search the Ziggurats and return with any information that you may discover.\n"] = {
		[1] = 5213,
	},
	["The Key to Karazhan V:60:Find Vandol. He is living somewhere on the eastern coast of Kalimdor, south of Theramore.:<Magus Halister carefully combs through the pages of thick tomes, his eyes scanning every line with an intensity that speaks of decades of study and experience. After several minutes of diligent searching, he finally looks up at you with a wry smile.>\n\nAh, yes. Vandol. He was here, in Theramore, some four years ago. Paid a visit to Lady Jaina, in fact. But he did not stay in the city for long. Found it too bustling for an old man like him, I suppose.\n\nAccording to our records, Vandol purchased a small boat not long after his visit. Loaded it up with vital supplies, food, and even seeds, if you can believe it. He set sail for the south, seeking a quieter life, I imagine. The coastline would be your best bet if you seek to find him."] = {
		[1] = 41137,
		[2] = 40821,
	},
	["Judgement's Wrists:60:Trade in your current item for the item that best suits your needs.:You wear the guise of Judgment, Paladin. I see it shine under the light of your faith, yet it seems rather dim. Perhaps the one you carry is not suited for the tasks you are willing to perform.\n\n<Geldra hums for a few seconds.>\n\nHand it here and tell me, what sins do you seek to judge?"] = {
		[1] = "Judgement's Wrists",
	},
	["Doomrigger's Clasp:60:Bring Doomrigger's Clasp to Mayara Brightwing in the Burning Steppes.:There is a chamber, high in Blackrock Spire, that was once called the Hall of Fortune.  It was where the Dark Iron dwarves kept their relics, trophies and objects of art.\n\nThat was long ago.  It is said the hall has collapsed and is now used for... less savory tasks.  But I believe some old dwarven relics may still be found there.\n\nOne such relic is Doomrigger's clasp, with a surface so encrusted with rare gems that it was said to make weep any dwarf who gazes upon it.\n\nThat clasp, Fanatique, is your goal."] = {
		[1] = 4764,
	},
	["Kharan Mighthammer:59:Travel to Blackrock Depths and find Kharan Mighthammer.\n\nThe King mentioned that Kharan was being held prisoner there - perhaps you should try looking for a prison.:You have been to the smoldering ruins of Thaurissan? Did you happen to run into a pitiful lout named Kharan Mighthammer? The dwarf that was supposedly watching over my baby girl!\n\n<The King sobs.>\n\nAnd now she's gone, Unknown!\n\nI have had my men turn the Steppes upside down. The only clue they have as to the whereabouts of my daughter is that she may be inside the Depths. For all I know, she could be dead!\n\nKharan is supposedly being held prisoner there... find him! I want answers!"] = {
		[1] = 4341,
	},
	["Avenger's Crown:60:Bring Vek'lor's Diadem, 2 Idols of Rebirth, 5 Stone Scarabs and 5 Crystal Scarabs to Andorgos in Ahn'Qiraj.  You must also attain Friendly reputation with the Brood of Nozdormu to complete this quest.:The Twin Emperors... their incessant whispers are slowly taking a toll on my sanity.  They mock me, knowing I cannot step further into their domain to save my brother Arygos.\n\nIn my visions I see their monstrous faces adorned by powerful crowns.  But I will have my revenge... I will transmute these symbols of Qiraji power to ones better suited to our needs.\n\nBring me the components I require, Fanatique.  I will give you a headpiece of unmatched power."] = {
		[1] = 8628,
	},
	["Lawbringer's Feet:60:Trade in your current item for the item that best suits your needs.:You wear the guise of the Lawbringer, Paladin. I see it shine under the light of your faith, yet it seems rather dim. Perhaps the one you carry is not suited for the tasks you are willing to perform.\n\n<Geldra hums for a few seconds.>\n\nHand it here and tell me, by which law shall your hand be guided?"] = {
		[1] = "Lawbringer's Feet",
	},
	["Lawbringer's Waist:60:Trade in your current item for the item that best suits your needs.:You wear the guise of the Lawbringer, Paladin. I see it shine under the light of your faith, yet it seems rather dim. Perhaps the one you carry is not suited for the tasks you are willing to perform.\n\n<Geldra hums for a few seconds.>\n\nHand it here and tell me, by which law shall your hand be guided?"] = {
		[1] = "Lawbringer's Waist",
	},
	["The Path of the Righteous:60:Collect 200 Silithid Carapace Fragments and return to Baristolth.:The Brood of Nozdormu are naturally distrusting of the lesser races. While it is true that you have proven to me that you have the potential makings of a hero, the time has come to prove this to my master.\n\nHive'Ashi, Hive'Zora, Hive'Regal: All swarming with activity and all a threat to our existence. Slay silithid at these hives and take from them a fragment of their carapace. When you can carry no more, return to me and I shall strengthen your resolve."] = {
		[1] = 8301,
	},
}
